DROP SCHEMA IF EXISTS DED;
CREATE SCHEMA DED;

DROP TABLE IF EXISTS DED.OPTY_EXTERNAL;

CREATE EXTERNAL TABLE DED.OPTY_EXTERNAL (
	UUID VARCHAR(100)
	, CREATED TIMESTAMP
	, REGION VARCHAR(100)
	, JOB_TITLE VARCHAR(100)
	, SALARY FLOAT
	, LOAN_AMOUNT FLOAT
	, PERIOD FLOAT
	, TARGET VARCHAR(1)
) AS COPY FROM '/tmp/data/*.parquet' PARQUET;


SELECT 
	CASE WHEN TARGET = 1 THEN 'POSITIVE' ELSE 'NEGATIVE' END AS 'RESULT'
	, CNT
FROM (
	SELECT TARGET, COUNT(*) AS CNT
	FROM DED.OPTY_EXTERNAL
	GROUP BY TARGET
) SRC
ORDER BY CNT DESC
;


SELECT 
	REGION
	, JOB_TITLE
	, CASE WHEN TARGET = 1 THEN 'POSITIVE' ELSE 'NEGATIVE' END AS 'RESULT'
	, COUNT(*) AS CNT
FROM DED.OPTY_EXTERNAL
GROUP BY REGION, JOB_TITLE, TARGET
ORDER BY CNT DESC
;
