/*
	Создаем внешнюю и внутреннюю таблицы 
	
	vsql -h34.71.139.131 -Udbadmin -f "D:\_git\andreev-ds-de-diploma\sql\CREATE_OPTY_TABLE.sql"
*/


DROP TABLE IF EXISTS DED.OPTY_EXTERNAL;
DROP TABLE IF EXISTS DED.OPTY;
DROP TABLE IF EXISTS DED.OPTY_Y_M_AGG; 
DROP TABLE IF EXISTS DED.OPTY_R_J_AGG; 

DROP SCHEMA IF EXISTS DED;
CREATE SCHEMA DED;

CREATE EXTERNAL TABLE DED.OPTY_EXTERNAL (
	UUID VARCHAR(100)
	, CREATED TIMESTAMP
	, REGION VARCHAR(100)
	, JOB_TITLE VARCHAR(100)
	, SALARY FLOAT
	, LOAN_AMOUNT FLOAT
	, PERIOD FLOAT
	, TARGET VARCHAR(1)
) AS COPY FROM '/tmp/data/*.parquet' PARQUET;

CREATE TABLE IF NOT EXISTS DED.OPTY (
	UUID VARCHAR(100) NOT NULL
	, LOAD_DT TIMESTAMP NOT NULL
	, CREATED TIMESTAMP NOT NULL
	, REGION VARCHAR(100) NOT NULL
	, JOB_TITLE VARCHAR(100) NOT NULL
	, SALARY FLOAT NOT NULL
	, LOAN_AMOUNT FLOAT NOT NULL
	, PERIOD INTEGER  NOT NULL
	, RES VARCHAR(3) NOT NULL
	
	, PRIMARY KEY (UUID)
)
	ORDER BY CREATED -- UUID
	-- SEGMENTED BY CREATED ALL NODES
;

CREATE TABLE DED.OPTY_Y_M_AGG (
	C_YEAR INTEGER NOT NULL
	, C_MONTH INTEGER NOT NULL
	, RES VARCHAR(3) NOT NULL
	, CNT INTEGER NOT NULL
) ORDER BY C_YEAR, C_MONTH;


CREATE TABLE DED.OPTY_R_J_AGG (
	REGION VARCHAR(100) NOT NULL
	, JOB_TITLE VARCHAR(100) NOT NULL
	, RES VARCHAR(3) NOT NULL
	, CNT INTEGER NOT NULL
) ORDER BY REGION, JOB_TITLE;

