/*
	ПЕРЕСЧИТЫВАЕМ АГГРЕГАТЫ
	
	vsql -h34.71.139.131 -Udbadmin -f "D:\_git\andreev-ds-de-diploma\sql\SP_CALC_AGG.sql"
*/

TRUNCATE TABLE DED.OPTY_Y_M_AGG;

INSERT INTO DED.OPTY_Y_M_AGG (C_YEAR, C_MONTH, RES, CNT) 
SELECT YEAR(CREATED) as C_YEAR, MONTH(CREATED) as C_MONTH, RES, COUNT(*) AS CNT 
FROM DED.OPTY
GROUP BY C_YEAR, C_MONTH, RES
;

COMMIT;


TRUNCATE TABLE DED.OPTY_R_J_AGG;

INSERT INTO DED.OPTY_R_J_AGG (REGION, JOB_TITLE, RES, CNT)
SELECT REGION, JOB_TITLE, RES, COUNT(*) AS CNT 
FROM DED.OPTY
GROUP BY REGION, JOB_TITLE, RES
;

COMMIT;

